# Generated by Django 4.1 on 2023-03-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviapage_search', '0002_operator_aircraft_home_base_aircraft_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='home_base',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='operator',
        ),
    ]
